# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='snap_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
